export enum ERRORS {
  INVALID_EMAIL = "admin.emailError",
  EMAIL_ALREADY_REGISTERED = "admin.emailExistsError",
  INVALID_PASSWORD = "home.newPasswordError",
  INVALID_CHANGE_PASSWORD = "home.oldPasswordError",
  PASSWORD_MATCH_OLD_PASSWORD = "home.samePasswordError",
  PROJECT_NAME_TOO_SHORT = "project.nameError",
  PROJECT_EXIST = "project.nameError2",
  FOLDER_IS_EMPTY = "project.folderNameError2",
  FOLDER_NOT_EXIST = "project.folderNameError2",
  FOLDER_EMPTY_OR_NOT_EXIST = "project.folderNameError2",
  TIF_OR_JPG_FILES_NOT_FOUND = "project.folderNameError3",
  MORE_OR_LESS_THAN_ONE_LAS_FILE = "project.folderNameError4",
  MORE_OR_LESS_THAN_ONE_CSV_FILE = "project.folderNameError5",
  NO_JPG_FILES = "project.folderNameError6",
  INVALID_FOLDER_FORMAT = "project.folderNameError7",
  INVALID_TIF_FILE = "project.tifError1",
  TIF_FILES_NOT_FOUND = "project.tifError2",
  INVALID_LOGIN_PASSWORD = "login.credentialsError",
  ML_MODEL_NAME_ALREADY_EXIST = "ml.nameError2",
  USER_NOT_FOUND = "restore.emailError",
  PROJECT_CREATION_FAILED = "project.error1",
  FOLDER_CREATION_FAILED = "project.error2",
  INSUFFICIENT_STORAGE = "project.error3",
  OTHER = "general.error",
}
