
services:
  react-app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
    
    env_file:
      - ./.env
