"""project preview layer id

Revision ID: 062fd5a64e64
Revises: e82f981d1969
Create Date: 2023-12-11 19:54:18.474065

"""
import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '062fd5a64e64'
down_revision = 'e82f981d1969'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("preview_layer_id", sa.String(), nullable=True, server_default=None)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "preview_layer_id")
    # ### end Alembic commands ###