"""feat ml model deeplab col

Revision ID: 347699a03658
Revises: 63b7f386c297
Create Date: 2024-05-21 16:36:33.222168

"""
import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '347699a03658'
down_revision = '63b7f386c297'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('ml_model_deeplab', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'ml_model_deeplab')
    # ### end Alembic commands ###
