"""project preview selected images

Revision ID: 59949d09fb54
Revises: 062fd5a64e64
Create Date: 2023-12-29 14:20:32.366395

"""
import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59949d09fb54'
down_revision = '062fd5a64e64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column('preview_selected_images', postgresql.ARRAY(sa.String), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "preview_selected_images")
    # ### end Alembic commands ###