"""users col external_user

Revision ID: 6bb2b7fcab13
Revises: ccdf301a728b
Create Date: 2023-08-23 14:52:16.385252

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6bb2b7fcab13"
down_revision = "986ce08556c5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("external_user", sa.Boolean(), nullable=True))
    users = sa.table("users", sa.column("external_user"))
    op.execute(users.update().values(external_user=True))
    op.alter_column("users", "external_user", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "external_user")
    # ### end Alembic commands ###
