"""ml effnetb0_051023 constant

Revision ID: 75014a2b15f0
Revises: 7a85d46faa11
Create Date: 2024-02-02 17:19:08.545819

"""
import sqlalchemy as sa

from alembic import op



# revision identifiers, used by Alembic.
revision = '75014a2b15f0'
down_revision = '7a85d46faa11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            INSERT
                INTO ml (name, link, type_of_data, type_of_objects, default_model, constant, created_at)
                VALUES ('effnetb0_051023', 'effnetb0_051023', array['panorama_360'], array['signboard'], True, True, '2023-12-04 00:00:01.000');
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM default_ml WHERE name='effnetb0_051023'")
    # ### end Alembic commands ###
