"""compare default value

Revision ID: 768a759c36d3
Revises: b794cb054f1c
Create Date: 2024-02-19 18:28:57.765808

"""

import sqlalchemy as sa

from alembic import op

from sqlalchemy.sql import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "768a759c36d3"
down_revision = "b794cb054f1c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
	op.execute(
        """
            do 
            $$
                declare
	                _id int;
	                project_1_name varchar;
  	                project_2_name varchar;
            begin
	            for _id, project_1_name, project_2_name in select id, project_1, project_2 from compare_projects
	            loop
		
		            declare date_1 varchar;
		            declare date_2 varchar;
		            begin
   		
   		                select date
   		                into date_1
   		                from projects
   		                where name = project_1_name;

   		                select date
   		                into date_2
   		                from projects
   		                where name = project_2_name;
   		
   		                update compare_projects set shooting_date_1 = date_1, shooting_date_2 = date_2
   		                where id = _id and length(shooting_date_1) is null;
		            end; 	
   	            end loop;
            end; 
            $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            update compare_projects set shooting_date_1 = null, shooting_date_2 = null;
        """
    )
    # ### end Alembic commands ###
