"""ml table

Revision ID: 770e5f520823
Revises: 1a9d329d75e2
Create Date: 2023-12-04 09:54:11.928450

"""
import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '770e5f520823'
down_revision = '1a9d329d75e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('type_of_data', postgresql.ARRAY(sa.String), nullable=True),
    sa.Column('type_of_objects', postgresql.ARRAY(sa.String), nullable=True),
    sa.Column('default_model', sa.Boolean(), default=False),
    sa.Column('constant', sa.Boolean(), default=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ml_id'), 'ml', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_id'), table_name='ml')
    op.drop_table('ml')
    # ### end Alembic commands ###
