"""ml buildings360_r50_250923 constant

Revision ID: 7a85d46faa11
Revises: a2c56b4edee0
Create Date: 2024-01-25 17:15:09.527035

"""
import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a85d46faa11'
down_revision = 'a2c56b4edee0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            UPDATE ml 
            SET constant = true 
            WHERE name = 'buildings360_r50_250923';
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            UPDATE ml 
            SET constant = false 
            WHERE name = 'buildings360_r50_250923';
        """
    )
    # ### end Alembic commands ###