"""username field

Revision ID: 874a7ba8624e
Revises: 02318f5d35b8
Create Date: 2023-06-07 20:43:46.166988

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "874a7ba8624e"
down_revision = "02318f5d35b8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "username")
    # ### end Alembic commands ###
