"""feat new model

Revision ID: 9119c61e12bb
Revises: 347699a03658
Create Date: 2024-05-29 12:13:19.396403

"""
import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9119c61e12bb'
down_revision = '347699a03658'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            INSERT
                INTO ml (name, link, type_of_data, type_of_objects, default_model, constant, created_at, status, view)
                VALUES ('yolov8x_satellite_base', 'yolov8x_satellite_base', array['satellite_images'], array['palm_tree', 'buildings', 'farms', 'trees'], True, False, '2024-05-29 00:00:01.000', 'Ready to use', 'yolov8');
        """
    )
    op.execute(
        """
            INSERT
                INTO ml (name, link, type_of_data, type_of_objects, default_model, constant, created_at, status, view)
                VALUES ('yolov8x_aerial_base', 'yolov8x_aerial_base', array['aerial_images'], array['palm_tree', 'buildings', 'farms', 'trees'], True, False, '2024-05-29 00:00:01.000', 'Ready to use', 'yolov8');
        """
    )
    op.execute(
        """
            UPDATE ml
            SET default_model = False
            WHERE id = 8;
        """
    )
    op.execute(
        """
            UPDATE ml
            SET default_model = False
            WHERE id = 9;
        """
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM ml WHERE name='yolov8x_satellite_base';")
    op.execute("DELETE FROM ml WHERE name='yolov8x_aerial_base';")
    op.execute(
        """
            UPDATE ml
            SET default_model = True
            WHERE id = 8;
        """
    )
    op.execute(
        """
            UPDATE ml
            SET default_model = True
            WHERE id = 9;
        """
    )
    # ### end Alembic commands ###
