"""restore access

Revision ID: 986ce08556c5
Revises: 531118454eef
Create Date: 2023-07-20 16:48:24.725225

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "986ce08556c5"
down_revision = "531118454eef"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "active_hash",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hash_key", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hash_key"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_active_hash_id"), "active_hash", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_active_hash_id"), table_name="active_hash")
    op.drop_table("active_hash")
    # ### end Alembic commands ###
