"""mlflow url

Revision ID: 9d983461d5c6
Revises: 4f70d5b78818
Create Date: 2024-04-23 13:59:29.911019

"""
import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d983461d5c6'
down_revision = '4f70d5b78818'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml', sa.Column('ml_flow_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ml', 'ml_flow_url')
    # ### end Alembic commands ###
