"""status project

Revision ID: aac4e54d4af2
Revises: fd9338ec1547
Create Date: 2023-09-15 22:03:35.575274

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "aac4e54d4af2"
down_revision = "fd9338ec1547"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("status", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "status")
    # ### end Alembic commands ###
