"""project col ml model

Revision ID: af47368c6bbc
Revises: 75014a2b15f0
Create Date: 2024-02-20 22:03:36.951124

"""
import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af47368c6bbc'
down_revision = '75014a2b15f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('ml_model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'ml_model')
    # ### end Alembic commands ###
