"""ml task id

Revision ID: b2e5d95dfd97
Revises: 752f9952ce2b
Create Date: 2024-03-19 17:42:54.493161

"""
import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2e5d95dfd97'
down_revision = '752f9952ce2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml', sa.Column('task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ml', 'task_id')
    # ### end Alembic commands ###
