"""view ml model

Revision ID: b758166ea80b
Revises: 1984357bace7
Create Date: 2024-05-20 16:26:28.470738

"""
import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b758166ea80b'
down_revision = '1984357bace7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml', sa.Column('view', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ml', 'view')
    # ### end Alembic commands ###
