"""ml status

Revision ID: c4c1007f1035
Revises: fbfbca29ea93
Create Date: 2024-03-19 18:13:30.566649

"""

import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c4c1007f1035"
down_revision = "fbfbca29ea93"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ml", sa.Column("status", sa.String(), nullable=True))
    op.execute(
        """
            UPDATE
                ml
            SET status = 'Ready to use'
            WHERE default_model = true;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ml", "status")
    # ### end Alembic commands ###
