"""add users

Revision ID: c4cba3c113e3
Revises: e6f95a29a307
Create Date: 2023-06-02 16:14:49.616000

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c4cba3c113e3"
down_revision = "e6f95a29a307"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            INSERT
                INTO users (email, username, created_at, password, role, is_active)
                VALUES ('user1@mail.ru', 'user2', '2023-05-31 15:15:12.341', '$2b$12$wpLMjUcvPzt/kuykml4FM.4Lh8ThI3cTvHpWekwTSVDbhKqiupN6i', 'user', true);
        """
    )
    op.execute(
        """
            INSERT
                INTO users (email, username, created_at, password, role, is_active)
                VALUES ('user2@mail.ru', 'user2', '2023-05-31 15:15:12.341', '$2b$12$o26H46QU2f9ZRDqv2iuhGeFOcxmXMfsdvUx/qvOvj7pXQt9qvkCJW', 'user', false);
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users WHERE email='user1@mail.ru';")
    op.execute("DELETE FROM users WHERE email='user2@mail.ru';")
    # ### end Alembic commands ###
