"""default ml classes

Revision ID: d0f5755b6785
Revises: f5ce9c1e1123
Create Date: 2023-12-06 16:33:00.814192

"""
import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0f5755b6785'
down_revision = 'f5ce9c1e1123'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            INSERT
                INTO ml_classes (name, type_of_objects, created_at)
                VALUES ('aerial_images', array['palm_tree', 'buildings', 'farms', 'trees', 'roads'], '2023-12-04 00:00:01.000');
        """
    )
    op.execute(
        """
            INSERT
                INTO ml_classes (name, type_of_objects, created_at)
                VALUES ('satellite_images', array['palm_tree', 'buildings', 'farms', 'trees', 'roads'], '2023-12-04 00:00:01.000');
        """
    )
    op.execute(
        """
            INSERT
                INTO ml_classes (name, type_of_objects, created_at)
                VALUES ('panorama_360', array['Lights pole', 'palm_tree', 'signboard', 'trees_group', 'trees_solo', 'traffic_sign', 'building', 'roads'], '2023-12-04 00:00:01.000');
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM ml_classes WHERE name='aerial_images'")
    op.execute("DELETE FROM ml_classes WHERE name='satellite_images'")
    op.execute("DELETE FROM ml_classes WHERE name='panorama_360'")
    # ### end Alembic commands ###