"""load default ml model

Revision ID: e0881d8abbd9
Revises: 770e5f520823
Create Date: 2023-12-04 10:01:08.739635

"""
import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0881d8abbd9'
down_revision = '770e5f520823'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            INSERT
                INTO ml (name, link, type_of_data, type_of_objects, default_model, constant, created_at)
                VALUES ('Aerial_HAT-L_SRx2_8985', 'Aerial_HAT-L_SRx2_8985', array['super_resolution'], array[''], True, False, '2023-12-04 00:00:01.000');
        """
    )
    op.execute(
        """
            INSERT
                INTO ml (name, link, type_of_data, type_of_objects, default_model, constant, created_at)
                VALUES ('Aerial_HAT-L_SRx3_8985', 'Aerial_HAT-L_SRx3_8985', array['super_resolution'], array[''], True, False, '2023-12-04 00:00:01.000');
        """
    )
    op.execute(
        """
            INSERT
                INTO ml (name, link, type_of_data, type_of_objects, default_model, constant, created_at)
                VALUES ('Aerial_HAT-L_SRx4_11980', 'Aerial_HAT-L_SRx4_11980', array['super_resolution'], array[''], True, False, '2023-12-04 00:00:01.000');
        """
    )
    op.execute(
        """
            INSERT
                INTO ml (name, link, type_of_data, type_of_objects, default_model, constant, created_at)
                VALUES ('buildings360_r50_250923', 'buildings360_r50_250923', array['panorama_360'], array['Lights pole', 'palm_tree', 'signboard', 'trees_group', 'trees_solo', 'traffic_sign', 'building', 'roads'], True, False, '2023-12-04 00:00:01.000');
        """
    )
    op.execute(
        """
            INSERT
                INTO ml (name, link, type_of_data, type_of_objects, default_model, constant, created_at)
                VALUES ('yolov8x_seg_360_1280_dataset_080123', 'yolov8x_seg_360_1280_dataset_080123', array['panorama_360'], array['Lights pole', 'palm_tree', 'signboard', 'trees_group', 'trees_solo', 'traffic_sign', 'building', 'roads'], True, False, '2023-12-04 00:00:01.000');
        """
    )
    op.execute(
       """
           INSERT
               INTO ml (name, link, type_of_data, type_of_objects, default_model, constant, created_at)
               VALUES ('r100_270923', 'r100_270923', array['aerial_images'], array['palm_tree', 'buildings', 'farms', 'trees', 'roads'], True, True, '2023-12-04 00:00:01.000');
       """
    )
    op.execute(
        """
            INSERT
                INTO ml (name, link, type_of_data, type_of_objects, default_model, constant, created_at)
                VALUES ('satellite_deeplabv3_plus_18122023', 'satellite_deeplabv3_plus_18122023', array['satellite_images'], array['palm_tree', 'buildings', 'farms', 'trees', 'roads'], True, True, '2023-12-04 00:00:01.000');
        """
    )
    op.execute(
        """
            INSERT
                INTO ml (name, link, type_of_data, type_of_objects, default_model, constant, created_at)
                VALUES ('satellite_yolov8l_18122023', 'satellite_yolov8l_18122023', array['satellite_images'], array['palm_tree', 'buildings', 'farms', 'trees', 'roads'], True, False, '2023-12-04 00:00:01.000');
        """
    )
    op.execute(
        """
            INSERT
                INTO ml (name, link, type_of_data, type_of_objects, default_model, constant, created_at)
                VALUES ('yolov8x_seg_aerial_1024_190823', 'yolov8x_seg_aerial_1024_190823', array['aerial_images'], array['palm_tree', 'buildings', 'farms', 'trees', 'roads'], True, False, '2023-12-04 00:00:01.000');
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM default_ml WHERE name='buildings360_r50_250923'")
    op.execute("DELETE FROM default_ml WHERE name='r100_270923'")
    op.execute("DELETE FROM default_ml WHERE name='satellite_deeplabv3_plus_18122023'")
    op.execute("DELETE FROM default_ml WHERE name='satellite_yolov8l_18122023'")
    op.execute("DELETE FROM default_ml WHERE name='yolov8x_seg_360_1280_dataset_080123'")
    op.execute("DELETE FROM default_ml WHERE name='yolov8x_seg_aerial_1024_190823'")
    # ### end Alembic commands ###
