"""add user admin

Revision ID: e6f95a29a307
Revises: 874a7ba8624e
Create Date: 2023-06-02 15:06:38.984605

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e6f95a29a307"
down_revision = "874a7ba8624e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            INSERT
                INTO users (email, username, created_at, password, role, is_active)
                VALUES ('admin@mail.ru', 'admin', '2023-05-31 15:15:12.341', '$2b$12$VaUQdeCnJbfiEr9MvwgLbu/doApKZW2taQ0oxx7d5D7nUyl643LEK', 'admin', true);
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users WHERE email='admin@mail.ru';")
    # ### end Alembic commands ###
