"""compare projects

Revision ID: e82f981d1969
Revises: d0f5755b6785
Create Date: 2023-12-11 09:56:32.235626

"""
import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e82f981d1969"
down_revision = "d0f5755b6785"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compare_projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_1", sa.String(), nullable=True),
        sa.Column("project_2", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("task_id", sa.String(), nullable=True, server_default=None),
        sa.Column("task_result", sa.JSON(), nullable=True),
        sa.Column("compare_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_compare_projects_id"), "compare_projects", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_compare_projects_id"), table_name="compare_projects")
    op.drop_table("compare_projects")
    # ### end Alembic commands ###
