"""ml classes

Revision ID: f5ce9c1e1123
Revises: e0881d8abbd9
Create Date: 2023-12-06 16:22:16.903874

"""
import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5ce9c1e1123'
down_revision = 'e0881d8abbd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type_of_objects', postgresql.ARRAY(sa.String), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ml_classes_id'), 'ml_classes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_classes_id'), table_name='ml_classes')
    op.drop_table('ml_classes')
    # ### end Alembic commands ###
