"""update ml view

Revision ID: f9ad2d9aaec7
Revises: b758166ea80b
Create Date: 2024-05-20 16:37:21.358096

"""
import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9ad2d9aaec7'
down_revision = 'b758166ea80b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            UPDATE ml
            SET view = 'yolov8'
            WHERE id = 5;
        """
    )
    op.execute(
        """
            UPDATE ml
            SET view = 'yolov8'
            WHERE id = 8;
        """
    )
    op.execute(
        """
            UPDATE ml
            SET view = 'yolov8'
            WHERE id = 9;
        """
    )
    op.execute(
        """
            UPDATE ml
            SET view = 'deeplabv3'
            WHERE id = 4;
        """
    )
    op.execute(
        """
            UPDATE ml
            SET view = 'deeplabv3'
            WHERE id = 6;
        """
    )
    op.execute(
        """
            UPDATE ml
            SET view = 'deeplabv3'
            WHERE id = 7;
        """
    )
    op.execute(
        """
            UPDATE ml
            SET view = 'panorama_360'
            WHERE id = 10;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            UPDATE ml
            SET view = NULL
            WHERE id = 5;
        """
    )
    op.execute(
        """
            UPDATE ml
            SET view = NULL
            WHERE id = 8;
        """
    )
    op.execute(
        """
            UPDATE ml
            SET view = NULL
            WHERE id = 9;
        """
    )
    op.execute(
        """
            UPDATE ml
            SET view = NULL
            WHERE id = 4;
        """
    )
    op.execute(
        """
            UPDATE ml
            SET view = NULL
            WHERE id = 6;
        """
    )
    op.execute(
        """
            UPDATE ml
            SET view = NULL
            WHERE id = 7;
        """
    )
    op.execute(
        """
            UPDATE ml
            SET view = NULL
            WHERE id = 10;
        """
    )
    # ### end Alembic commands ###